# Workflow to push to npmjs. 
name: deploy
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x
        registry-url: https://registry.npmjs.org/

    # Install
    - name: install
      run: cd ./package && npm install

    # Build
    - name: build
      run: cd ./package && npm run build
        
    # Run tests
    - name: test
      run: cd ./package && npm test

    # Copy license
    - name: copy license
      run: cd ./package && cp ../LICENSE .

    # Publish to npm
    - name: publish
      run: cd ./package && npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}